[workspace]
resolver = "2"

members = ["day-one", "day-three", "day-two"]

[workspace.dependencies]
anyhow = "1.0.93"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
dotenv = "0.15.0"
nom = "7.1.3"
itertools = "0.13.0"
